# Generated by Django 5.2.8 on 2025-12-19 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('smartwatch', 'Smart Watch'), ('fitness_band', 'Fitness Band'), ('phone', 'Phone'), ('smart_scale', 'Smart Scale'), ('heart_rate_monitor', 'Heart Rate Monitor'), ('blood_pressure', 'Blood Pressure Monitor'), ('other', 'Other')], default='smartwatch', max_length=20)),
                ('manufacturer', models.CharField(choices=[('apple', 'Apple'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('huawei', 'Huawei'), ('amazfit', 'Amazfit'), ('withings', 'Withings'), ('polar', 'Polar'), ('other', 'Other')], default='other', max_length=20)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('connection_type', models.CharField(choices=[('bluetooth', 'Bluetooth'), ('wifi', 'Wi-Fi'), ('usb', 'USB'), ('cloud', 'Cloud API')], default='bluetooth', max_length=20)),
                ('bluetooth_address', models.CharField(blank=True, max_length=17, null=True)),
                ('bluetooth_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('device_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('syncing', 'Syncing'), ('paired', 'Paired'), ('error', 'Error'), ('low_battery', 'Low Battery')], default='disconnected', max_length=20)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('supported_metrics', models.JSONField(blank=True, default=list)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('hardware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('software_version', models.CharField(blank=True, max_length=50, null=True)),
                ('auto_sync', models.BooleanField(default=True)),
                ('sync_frequency', models.IntegerField(default=15)),
                ('sync_on_startup', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_synced', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(max_length=20)),
                ('attempted_at', models.DateTimeField()),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('apple', 'Apple'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('huawei', 'Huawei'), ('amazfit', 'Amazfit'), ('withings', 'Withings'), ('polar', 'Polar'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('driver_class', models.CharField(max_length=200)),
                ('connection_types', models.JSONField(default=list)),
                ('capabilities', models.JSONField(default=dict)),
                ('config_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('scheduled', 'Scheduled'), ('background', 'Background')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('data_synced', models.JSONField(blank=True, default=dict)),
                ('metrics_count', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
