# Generated by Django 5.2.8 on 2025-12-19 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceconnectionlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicedatacache',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_cache', to='devices.device'),
        ),
        migrations.AlterUniqueTogether(
            name='devicedriver',
            unique_together={('manufacturer', 'version')},
        ),
        migrations.AddField(
            model_name='devicesynclog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'is_connected'], name='devices_dev_user_id_e188a3_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['bluetooth_address'], name='devices_dev_bluetoo_e32bba_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='devices_dev_device__e2c19e_idx'),
        ),
        migrations.AddIndex(
            model_name='devicedatacache',
            index=models.Index(fields=['device', 'data_type', 'date'], name='devices_dev_device__d17b42_idx'),
        ),
        migrations.AddIndex(
            model_name='devicedatacache',
            index=models.Index(fields=['expires_at'], name='devices_dev_expires_c302eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicedatacache',
            unique_together={('device', 'data_type', 'date')},
        ),
    ]
