# Generated by Django 5.2.8 on 2025-12-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg_heart_rate', models.FloatField(null=True)),
                ('total_steps', models.IntegerField(default=0)),
                ('sleep_hours', models.FloatField(default=0)),
            ],
        ),
    ]
