# Generated by Django 5.2.8 on 2025-12-19 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        ('health_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthinsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heartratereading',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heart_rate_readings', to='devices.device'),
        ),
        migrations.AddField(
            model_name='heartratereading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sleepsession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sleep_sessions', to='devices.device'),
        ),
        migrations.AddField(
            model_name='sleepsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'start_time'], name='activities_user_id_8ada53_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activities_activit_f14342_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'activity_type', 'start_time'], name='activities_user_id_1113be_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['data_hash'], name='activities_data_ha_289727_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['user', 'date'], name='daily_summa_user_id_4b4570_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['date'], name='daily_summa_date_4d8318_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['user', 'overall_score'], name='daily_summa_user_id_18e735_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['user', 'is_read'], name='health_aler_user_id_9176b0_idx'),
        ),
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['user', 'alert_type'], name='health_aler_user_id_0f7f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['user', 'severity'], name='health_aler_user_id_087a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['triggered_at'], name='health_aler_trigger_dbd04f_idx'),
        ),
        migrations.AddIndex(
            model_name='healthgoal',
            index=models.Index(fields=['user', 'is_active'], name='health_goal_user_id_dcde6b_idx'),
        ),
        migrations.AddIndex(
            model_name='healthgoal',
            index=models.Index(fields=['user', 'goal_type'], name='health_goal_user_id_df7acc_idx'),
        ),
        migrations.AddIndex(
            model_name='healthgoal',
            index=models.Index(fields=['user', 'is_primary'], name='health_goal_user_id_936f60_idx'),
        ),
        migrations.AddIndex(
            model_name='healthinsight',
            index=models.Index(fields=['user', 'is_new'], name='health_insi_user_id_da5d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='healthinsight',
            index=models.Index(fields=['user', 'category'], name='health_insi_user_id_5db964_idx'),
        ),
        migrations.AddIndex(
            model_name='healthinsight',
            index=models.Index(fields=['user', 'insight_type'], name='health_insi_user_id_afb3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='healthinsight',
            index=models.Index(fields=['generated_at'], name='health_insi_generat_85896c_idx'),
        ),
        migrations.AddIndex(
            model_name='heartratereading',
            index=models.Index(fields=['user', 'timestamp'], name='heart_rate__user_id_83f4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='heartratereading',
            index=models.Index(fields=['timestamp'], name='heart_rate__timesta_ef3408_idx'),
        ),
        migrations.AddIndex(
            model_name='heartratereading',
            index=models.Index(fields=['user', 'is_anomaly'], name='heart_rate__user_id_bd8a21_idx'),
        ),
        migrations.AddIndex(
            model_name='heartratereading',
            index=models.Index(fields=['data_hash'], name='heart_rate__data_ha_344328_idx'),
        ),
        migrations.AddIndex(
            model_name='sleepsession',
            index=models.Index(fields=['user', 'start_time'], name='sleep_sessi_user_id_45b400_idx'),
        ),
        migrations.AddIndex(
            model_name='sleepsession',
            index=models.Index(fields=['start_time', 'end_time'], name='sleep_sessi_start_t_3a99cf_idx'),
        ),
        migrations.AddIndex(
            model_name='sleepsession',
            index=models.Index(fields=['user', 'quality_score'], name='sleep_sessi_user_id_33e955_idx'),
        ),
        migrations.AddIndex(
            model_name='sleepsession',
            index=models.Index(fields=['data_hash'], name='sleep_sessi_data_ha_6143ab_idx'),
        ),
    ]
